### ISSUE TITLE
RPM installation for PupNet HelloWorld has a missing requirement

### ISSUE THREAD

**Issue by stuarthillary** [kuiperzone/PupNet-Deploy#10]
I successfully installed the RPM package for the PupNet HelloWorld application on RHEL 8.7.

The application aborts when running it

```
> helloworld
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.TextInfo..cctor()
   at System.String.ToLowerInvariant()
   at System.Text.EncodingHelper.GetCharset()
   at System.Text.EncodingHelper.GetEncodingFromCharset()
   at System.ConsolePal.GetConsoleEncoding()
   at System.Console.get_OutputEncoding()
   at System.Console.CreateOutputWriter(System.IO.Stream)
   at System.Console.<get_Out>g__EnsureInitialized|26_0()
   at System.Console.get_Out()
   at System.Console.WriteLine(System.String)
   at HelloWorld.Program.Main(System.String[])
```

In this case, the helloworld application is not running in globalization invariant mode and thus requires the package `libicu` to be installed.

https://learn.microsoft.com/en-us/dotnet/core/runtime-config/globalization
https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md

From my limited understanding of RPM spec files, adding `libicu` to the `Requires` section of the spec file may fix this. Is there currently a way of controlling prerequisites for the RPM package creation using pupnet configuration?

Outside of this helloworld example, a .NET application may have more exotic package requirements e.g. if they make use of native Linux libraries.

**Comment by kuiperzone** [comment]
Thank you for the reply and suggestion. First off, I am curious:

If I understand you correctly, you say the RPM package of "Hello World" won't run because of a dependency, but the RPM package of PupNet-Deploy runs fine...

>There is a workaround though, which is to use the RPM package for PupNet installation.
https://github.com/kuiperzone/PupNet-Deploy/issues/8

Seems surprising?

But, yes, I can see the argument for including a "Requires" section in the configuration for RPM (and presumably for .deb files as well). I agree this is important especially if the app is using native linux libraries.

However, I remain a little disappointed with dotnet. Please correct me if my thinking here is misguided, but I had understood that a "self-contained" app deployed with all its runtime dependencies at least, I guess, for most non-exotic scenarios. It is disappointing therefore to see a "Hello World" app fail on a major distro such as RHEL.

**Comment by stuarthillary** [comment]
> If I understand you correctly, you say the RPM package of "Hello World" won't run because of a dependency, but the RPM package of PupNet-Deploy runs fine...
> 
> > There is a workaround though, which is to use the RPM package for PupNet installation.
> > #8
> 
> Seems surprising?

At a guess, this maybe because a dotnet tool would use invariant mode and so not run up against this particular problem?

> However, I remain a little disappointed with dotnet. Please correct me if my thinking here is misguided, but I had understood that a "self-contained" app deployed with all its runtime dependencies at least, I guess, for most non-exotic scenarios. It is disappointing therefore to see a "Hello World" app fail on a major distro such as RHEL.

This was a conscious decision on behalf of the dotnet team, I think, look at the arguments in this section
https://github.com/dotnet/runtime/blob/main/docs/design/features/globalization-invariant-mode.md#background

As an aside, other possible dependencies are listed here
https://learn.microsoft.com/en-us/dotnet/core/install/linux-scripted-manual#rpm-dependencies

Whether these dependencies are required will depend on what functionality the app uses, and right now this places the onus on any .NET package authors and/or sysadmins.

**Comment by kuiperzone** [comment]
That is an incredibly helpful reply. Thank you. I'm looking in to it.

**Comment by stuarthillary** [comment]
I just found this additional advice for when installation of dependent packages is undesirable
https://github.com/dotnet/core/blob/main/Documentation/self-contained-linux-apps.md

Looks to be quite an error prone procedure that requires a lot of testing.

**Comment by kuiperzone** [comment]
Hi @stuarthillary 

Check out the latest version 1.3.0 which now supports dependencies for RPM and DEB. I've tested the HelloWorld RPM on a clean install of Alma 9, and it seems to work.
