### ISSUE TITLE
Inno Setup fails with x86

### ISSUE THREAD

**Issue by mysteryx93** [kuiperzone/PupNet-Deploy#21]
If I try to publish an app with runtime `win-x86` with kind=setup, the ISS file contains

```
ArchitecturesAllowed=x86
ArchitecturesInstallIn64BitMode=x86
```

and it throws

> Error on line 19 in C:\Users\Hanuman\AppData\Local\Temp\KuiperZone.PupNet\player432hz-win-x86-Release-Setup\Player432Hz.iss: Value of [Setup] section directive "ArchitecturesInstallIn64BitMode" is invalid.

**Comment by kuiperzone** [comment]
Hopefully fixed in 1.6
