### ISSUE TITLE
Create a docker image

### ISSUE THREAD

**Issue by amitza** [kuiperzone/PupNet-Deploy#29]
The Linux installation of PupNet-Deploy can take a lot of time because of the number of packages needed (more than 193).
In order to save this setup time the CLI can be exposed as a docker container. With docker the usage will be a one-liner:
```
docker run pupnet-deploy -v $(pwd):/workspace-folder/ pupnet --runtime linux-x64 --kind appimage
```

**Comment by kuiperzone** [comment]
Thank you. But your comment is not clear. Are you asking for a feature or offering advice to users? Are you asking that pupnet be packaged as a container?

Ensuring that pupnet can be used with docker efficiently is something I'm interested. Can you be more explicit?
