### ISSUE TITLE
Add multiple project support for different OS

### ISSUE THREAD

**Issue by Juff-Ma** [kuiperzone/PupNet-Deploy#30]
Could you make it possible to define multiple Projects in the pupnet.conf for when you have got multiple projects for different os (ExampleApp.Gui.Win32, ExampleApp.Gui.Gtk, ExampleApp.Gui.Mac or similar)? i haven't found a way to do this in the current state.

**Comment by kuiperzone** [comment]
You could disable the publish call by setting `DotnetProjectPath` to "NONE", and instead have `DotnetPostPublish` (and `DotnetPostPublishOnWindows`) points to scripts which perform the publish of custom projects. If you need to switch in the script, then all the macros are exported as environment variable and you could use `${DOTNET_RUNTIME}`.

In the future, I may add an macro variable or two to make this a little easier.

**Comment by kuiperzone** [comment]
In upcoming version 1.8, you will be able to supply the csproj file from the command line. You will also be able to supply property DefineConstants from the command line also, which can be used in project files.
