### ISSUE TITLE
Can this be a dotnet tool?

### ISSUE THREAD

**Issue by malgreen** [kuiperzone/PupNet-Deploy#5]
I think this would would be _even_ better if it was packaged as a dotnet tool (see [this](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools-how-to-create)), and uploaded to NuGet.
Short term this could make installation easier, and longer term this could lead to PupNet being easily used in GitHub Actions for Continuous Delivery - AFAIK InnoSetup is also installed on the GitHub Actions Windows runner.

**Comment by kuiperzone** [comment]
Wow! I wasn't actually aware of this. Will look into it.

**Comment by Malgreen** [comment]
Sounds great, thanks!

**Comment by kuiperzone** [comment]
OK. Done it. See below and version 1.2 for new features. Thanks for the suggestion.

https://www.nuget.org/packages/KuiperZone.PupNet/1.2.0
